import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import VueParticles from "vue-particles";
import { createPinia } from 'pinia';
const app = createApp(App);
app.use(createPinia());
app.use(VueParticles);
app.use(router);
app.mount('#app');
